apiVersion: apps/v1
kind: Deployment
metadata:
  name: bug-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bug-backend
  template:
    metadata:
      labels:
        app: bug-backend
    spec:
      containers:
      - name: bug-backend
        image: bug-backend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: MLFLOW_ALLOW_FILE_STORE
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: bug-backend-service
spec:
  selector:
    app: bug-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
